### ISSUE TITLE
Issues when starting pyplanet_dedicated_docker_controller_1

### ISSUE THREAD

**Issue by SebPikPik** [PyPlanet/docker#1]
Hi,

Whenever I start (even after fresh build) the docker cluster, I have this error below. Any idea ?

```
INFO     [Main][pyplanet.core.management.commands.start] Initiated configuration and environment...
INFO     [Main][pyplanet.core.management.commands.start] -------------------------------[  PyPlanet v0.6.4  ]-------------------------------
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
INFO     [Main][pyplanet.god.process] Starting pool process for 'default'...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyplanet/god/process.py", line 46, in _run
    instance = Controller.prepare(name).instance
  File "/usr/local/lib/python3.6/site-packages/pyplanet/core/controller.py", line 18, in prepare
    self.__instance = Instance(name)
  File "/usr/local/lib/python3.6/site-packages/pyplanet/core/instance.py", line 75, in __init__
    self.storage =                              Storage.create_from_settings(self, settings.STORAGE[self.process_name])
  File "/usr/local/lib/python3.6/site-packages/pyplanet/core/storage/storage.py", line 49, in create_from_settings
    return cls(instance, driver, storage_config)
  File "/usr/local/lib/python3.6/site-packages/pyplanet/core/storage/storage.py", line 40, in __init__
    self._tmp_root = os.path.join(settings.TMP_PATH, self._instance.process_name)
  File "/usr/local/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
CRITICAL [Main][pyplanet.god.pool] The instance 'default' just died. We will not restart!
CRITICAL [Main][pyplanet.god.pool] All instances died. Quitting now...
```

**Comment by tomvlk** [comment]
@Evilcious things will be refactored, please use the new docker setup that will be available soon in the main repo
